# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module T::CompatibilityPatches::RSpecCompatibility::MethodDoubleExtensions; end
module T::CompatibilityPatches::RSpecCompatibility::RecorderExtensions; end
module WidgetsInc::Types::Array; end
module WidgetsInc::Types::Strict::Float; end
module WidgetsInc::Types::Strict::Integer; end
module WidgetsInc::Types::Strict::String; end
